### PR TITLE
Data nav

### PR DESCRIPTION
**Pull request by sri2k1us**
Changes for using `react-query` and dynamic routing for data. This still requires lot of clean up and testing. @psarando  @ash3rz  - Please makes changes as required and merge at your convenience.

### CODE REVIEW

**Comment by ash3rz** [comment]
I think you've started breaking up this PR into multiple smaller PRs - maybe we can close this one now?  (Though we still need to evaluate react-query, I am interested in trying that out and switching over)

**Comment by sri2k1us** [comment]
> I think you've started breaking up this PR into multiple smaller PRs - maybe we can close this one now? (Though we still need to evaluate react-query, I am interested in trying that out and switching over)

Sounds good. You can take over react-query. I will probably move onto `Apps`.

**Comment by ash3rz** [comment]
> Sounds good. You can take over react-query. I will probably move onto `Apps`.

Oh, I didn't mean to imply I wanted to take it from you, just that I'm interested in it being integrated.  I can take it on if you'd rather move onto Apps though.

**Comment by sri2k1us** [comment]
> > Sounds good. You can take over react-query. I will probably move onto `Apps`.
> 
> Oh, I didn't mean to imply I wanted to take it from you, just that I'm interested in it being integrated. I can take it on if you'd rather move onto Apps though.

I think its probably a good idea for you handle the transition for data portion anyway since you worked on most of it and you will be more comfortable. I already started on app listing. I am using react-query for apps as well.

**Pull request closed without merging**
