### PR TITLE
core-1456 Update sidebar menu color.

### PR DESCRIPTION
**Pull request by sri2k1us**
image

image

image

### CODE REVIEW

**Review by psarando — CHANGES_REQUESTED** [review]
LGTM 👍  but is there a reason for this change?
Is this the standard CyVerse colors now for app side-bars and toolbars?

These magic numbers are now repeated in a few locations, but they probably should come from named constants somewhere, or from fields in our theme (e.g. `theme.palette.main-side-bar` and `theme.palette.main-app-bar` perhaps):
https://github.com/cyverse-de/sonora/blob/3071bf50a9a46b3dab7d383cc47a2150c1caba34/src/components/theme/default/index.js#L1-L5

**Comment by sri2k1us** [comment]
> LGTM 👍 but is there a reason for this change?
> Is this the standard CyVerse colors now for app side-bars and toolbars?
> 
> These magic numbers are now repeated in a few locations, but they probably should come from named constants somewhere, or from fields in our theme (e.g. `theme.palette.main-side-bar` and `theme.palette.main-app-bar` perhaps):
> https://github.com/cyverse-de/sonora/blob/3071bf50a9a46b3dab7d383cc47a2150c1caba34/src/components/theme/default/index.js#L1-L5

These changes were requested by Nirav for 2 reasons:
- Better contrast against highlight color
- Match AppBar color to User Portal color

But I don't think we will need to update the `primary` color. 

Adding to themes sounds like a good idea especially if we want to do a dark mode.

**Review by ash3rz — APPROVED** [review]
LGTM :shipit:

**Review by psarando — APPROVED** [review]
LGTM :shipit: 👍

**Comment by sri2k1us** [comment]
Thanks for the review.

**Pull request merged**
