### PR TITLE
CORE-2002 VICE Countdown Timers

### PR DESCRIPTION
**Pull request by psarando**
This PR will add countdown timers for running VICE analyses in the listing, submission landing, and the dashboard.

---

Analysis Listing:
Analysis Listing Countdown Timer

---

Analysis Landing page:
Analysis Landing Countdown Timer

---

Dashboard Item:
Analysis Dashboard Item Countdown Timer

### CODE REVIEW

**Comment by niravmerchant** [comment]
I would prefer time to be hours:min no need for seconds. If we can say Time Remaining: HH:MM that would be better

**Review by slr71 — APPROVED** [review]
The code looks good to me! I think Nirav had a small request to change the time limit display.

**Review by slr71 — APPROVED** [review]
LGTM 👍

**Comment by psarando** [comment]
Here are the screenshots for the original countdown format for comparison:

---

Analysis Listing:
Analysis Listing Countdown Timer

---

Analysis Landing page:
Analysis Landing Countdown Timer

---

Dashboard Item:
Analysis Dashboard Item Countdown Timer

---

Here are the screenshots for the previous countdown format for comparison:

---

Analysis Listing:
Analysis Listing Countdown Timer

---

Analysis Landing page:
Analysis Landing Countdown Timer

---

Dashboard Item:
Analysis Dashboard Item Countdown Timer

**Comment by psarando** [comment]
Thanks for the reviews! 👍

**Pull request merged**
