### PR TITLE
Remove dividers from the dashboard

### PR DESCRIPTION
**Pull request by johnworth**
SSIA. Adjusts the bottom margin to increase the spacing between sections.

### CODE REVIEW

**Comment by johnworth** [comment]
Forgot to include pictures.

**Comment by johnworth** [comment]
image

image

**Comment by johnworth** [comment]
Oops, accidentally caught the snipping tool in one of the screenshots. Oh, well.

**Review by sri2k1us — APPROVED** [review]
LGTM :shipit:

**Review by ash3rz — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
