### PR TITLE
CORE-1120: call the `/secured/notifications/messages` endpoint instea…

### PR DESCRIPTION
**Pull request by slr71**
…d of the `/secured/notifications/last-ten-messages` endpoint

### CODE REVIEW

**Review by sri2k1us — APPROVED** [review]
LGTM :shipit:

**Review by ash3rz — APPROVED** [review]
:shipit:

**Review by psarando — APPROVED** [review]
LGTM :shipit:

**Comment by slr71** [comment]
Thanks for the reviews!

**Pull request merged**
