### PR TITLE
Show Manage Tools button in `small` screen.

### PR DESCRIPTION
**Pull request by sri2k1us**
- Large Screen
image
- Small Screen
image
- Mobile
image

### CODE REVIEW

**Review by ianmcorvidae — APPROVED** [review]
Seems reasonable to me. I guess the summary here is changing `smDown` -> `xsDown` makes the button visible in `small`, and removing the `isMobile` check also ensures that the button always appears any time the dot menu does?

**Comment by sri2k1us** [comment]
> Seems reasonable to me. I guess the summary here is changing `smDown` -> `xsDown` makes the button visible in `small`, and removing the `isMobile` check also ensures that the button always appears any time the dot menu does?

I couldn't have summarized this change any better. 🎉

**Review by ash3rz — APPROVED** [review]
:shipit:

**Comment by sri2k1us** [comment]
Thanks for the reviews.

**Pull request merged**
